/*
   * Tansaku
   * A search engine of sorts (written more as a proof of concept)
   * 2016 Gautam Mittal
*/

const fs = require('graceful-fs');
const lemmer = require('lemmer');
const nj = require(__dirname+'/util/numjs.min');
const sw = require('stopword');
const util = require(__dirname+'/util/util');

// As generated by format.js from index.json as generated by crawl.js
const database = JSON.parse(fs.readFileSync(__dirname+'/formatted.json', 'utf-8'));

function vectorMagnitude(v) {
  v = nj.multiply(v, v);
  var magnitude = 0;
  for (var i = 0; i < v.shape[0]; i++) {
    magnitude += v.get(i);
  }

  var r = Math.sqrt(magnitude);
  return r;
}

function cosineSimilarity(v1, v2) {
  return nj.dot(v1, v2).get(0) / (vectorMagnitude(v1) * vectorMagnitude(v2));
}

function search(query) {
  // Preprocess query string
  query = query.toLowerCase()
  .replace(/\W/g, ' ')
  .split(" ")
  .filter(function(element) {
    return element !== "";
  });

  query = sw.removeStopwords(query);
  lemmer.lemmatize(query, function (err, words) {
    if (err) throw err;

    query = words.slice();
    var queryVector = nj.array(util.vectorize(query, database.vectorIndex));

    var ranks = [];
    var results = [];

    Object.keys(database).forEach(function (id) {
      if (id != "vectorIndex" && id != "links") {
        ranks.push(cosineSimilarity(queryVector, nj.array(database[id].data)));
        results.push({"title": database[id].title, "url": database[id].url});
      }
    });

    console.log(util.sortFromArray(ranks, results));

  });
}

// If search query contains terms that is not in vectorIndex, cosineSimilarity will return NaN (e.g. "hello world")
search("problems involving numbers by gautam mittal");
